version: '3'
services:
  nginx:
    image: nginx:stable
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx/error.log:/etc/nginx/error_log.log
      - ./config/cert/nginx.crt:/etc/nginx/cert/nginx.crt
      - ./config/cert/nginx.key:/etc/nginx/cert/nginx.key
      - ./.cache/:/etc/nginx/cache
    ports:
      - 80:80
      - 443:443
    links:
      - "app"
  app:
    image: node:10.15.3-alpine
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - NUXT_HOST=0.0.0.0
    command: sh -c "yarn clean && yarn build && yarn start"
